# Generated by Django 2.2.1 on 2019-06-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to='justPost.Profile'),
        ),
    ]
